name: nbpweb
channels:
  - conda-forge
dependencies:
        - flask
        - geopandas
        - shapely
        - netcdf4
        - xarray
        - numpy
        - matplotlib
        - zeep
        - xmltodict
